spring:
  application:
    name: api-gateway
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
zuul:
  routes:
    userprovider001:
      path: /userprovider001/**
      url: http://localhost:9003/
    userprovider002:
      path: /userprovider002/**
      url: http://localhost:9004/
    userprovider:
      path: /service/**
      service-id: USERPROVIDER
  retryable: true   #打开重试
ribbon:
  ConnectionTimeOut: 250
  ReadTimeout: 1000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
#设定Hystrix熔断超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

